### ISSUE TITLE
File field issue

### ISSUE THREAD

**Issue by Elshaden** [wdelfuego/nova-wizard#1] opened 2023-10-30 20:49 UTC
Hi
Thanks for this package,
The file field is not rendered properly and takes a very large width , that you need to scroll side panel to see the form

Thanks

**Comment by wdelfuego** [comment] 2023-10-31 13:37
Thanks for reporting! I'll try to look into this soon. PRs are welcome in case anyone can do a CSS fix.

**Comment by wdelfuego** [comment] 2023-11-03 17:09
I can't reproduce the issue in Safari or Chrome under macOS, if anything, the field is not using up enough horizontal width.

Are your Nova assets up to date?

Can you share a screenshot and specify your browser/OS?

**Comment by wdelfuego** [comment] 2023-11-09 20:11
Hi @Elshaden, any update :)?

**Comment by wdelfuego** [comment] 2023-11-16 08:56
Closing issue due to lack of information, please update with a screenshot and info about the browser and OS if the problem persists.

**Closed as completed by wdelfuego** 2023-11-16 08:56 UTC
Labels: help wanted, question, missing info
